//! Focused policy staging and predicate scenarios.

mod absent_and_incompatible_contexts_are_unavailable_without_inferred_conversion;
mod bands_apply_directional_hysteresis_without_resetting_on_unavailability;
mod changed_uses_canonical_identity_and_named_references;
mod condition_configuration_validates_predicate_type_thresholds_and_bands;
mod condition_id_is_stable_target_local_identity;
mod crossing_refuses_an_unparseable_persisted_predecessor;
mod numeric_delta_predicates_are_exact_and_failure_aware;
mod ordered_crossing_and_level_predicates_have_their_specified_triggers;
mod policy_configuration_is_a_hard_schema_twelve_contract;
mod policy_staging_exposes_every_m2_routing_eligibility_without_delivery;
mod policy_staging_keeps_the_four_t0_branches_disjoint_and_side_effect_free;
mod policy_staging_rejects_current_observations_outside_the_target_contract;
mod policy_values_cover_each_typed_comparison_and_exact_arithmetic_path;
mod support;
mod text_conditions_are_changed_only_with_exact_unicode_identity;
