//! Focused runtime-lifecycle scenarios.

mod contract_change_is_refused_without_state_mutation_until_blind_reset;
mod decimal_observations_preserve_evidence_and_normalize_comparison;
mod direct_acquisition_fetch_and_error_helpers_cover_scalar_transport_boundaries;
mod dry_runs_classify_failure_branches_without_writing_temporal_state;
mod durable_outbox_retries_stored_bytes_terminally_fails_and_never_evicts_pending_records;
mod every_m3_source_failure_class_persists_its_closed_health_reason;
mod failure_branches_preserve_preexisting_measurement_and_condition_facts;
mod html_http_input_uses_the_final_response_url_as_its_htmlcut_base;
mod html_text_and_attribute_acquisition_persist_original_evidence_and_htmlcut_identity;
mod html_text_dom_canonicalization_parses_clone_text_while_persisting_original_evidence;
mod html_text_projections_expose_plain_and_structural_semantics;
mod htmlcut_canonicalization_preflight_rejections_retain_evidence_for_the_full_lifecycle;
mod htmlcut_failures_keep_candidate_counts_and_reasons_in_the_source_health_detail;
mod htmlcut_invalid_selector_begins_a_permanent_contract_error_episode;
mod http_fetch_handles_success_and_transport_failure_statuses;
mod http_fetch_retains_the_final_redirect_url_for_html_input_construction;
mod lifecycle_facet_exposes_durable_and_staged_state_without_events;
mod live_runtime_persists_level_hysteresis_between_runs;
mod live_runtime_stages_named_conditions_against_pre_run_temporal_state;
mod lowering_max_attempts_dead_letters_an_exhausted_pending_record_without_another_process_run;
mod named_conditions_keep_last_transition_references_independent;
// These scenarios exercise POSIX permissions, FIFOs, symbolic links, or `/bin/sh` delivery.
#[cfg(unix)]
mod non_lockable_lock_nodes_surface_io_errors;
#[cfg(unix)]
mod normal_state_io_refuses_symlinked_storage_nodes_while_reset_remains_blind;
#[cfg(unix)]
mod outbox_delivery_never_runs_before_the_state_and_event_commit;
mod owned_storage_without_a_state_file_loads_as_pending;
mod permanent_json_pointer_errors_form_one_episode_without_touching_source_health;
mod persisted_htmlcut_diagnostics_are_revalidated_before_runtime_use;
mod persisted_parse_diagnostics_are_refused_without_state_mutation;
mod policy_semantics_changes_reset_every_projection_while_htmlcut_is_html_only;
#[cfg(unix)]
mod post_commit_outbox_write_failures_remain_structured_delivery_evidence;
mod predecessor_schemas_are_rejected_without_migration_and_reset_remains_blind;
mod reset_does_not_materialize_delivery_for_a_permanent_projection_contract_error;
mod reset_of_a_valid_target_without_on_run_routes_has_no_delivery_evidence;
mod reset_remains_blind_when_the_remaining_target_is_semantically_invalid;
mod reset_removes_only_the_v2_storage_root_without_inspecting_other_paths;
mod reset_reports_only_the_v2_storage_root_and_recovers_a_malformed_root_node;
#[cfg(unix)]
mod reset_stages_and_delivers_one_durable_reset_event_after_the_blind_delete;
mod root_json_pointer_selects_a_root_scalar_as_exact_evidence;
mod run_and_status_distinguish_semantic_target_and_target_relative_state_failures;
mod run_status_batch_and_persistence_cover_the_v2_lifecycle;
mod shared_status_lock_waits_for_a_live_run_lock_to_be_released;
#[cfg(unix)]
mod source_and_permanent_failures_preserve_persist_failure_reports;
mod source_suspect_failures_persist_health_without_advancing_the_accepted_baseline;
#[cfg(unix)]
mod state_io_reports_permission_failures_and_does_not_hide_persist_failure;
mod storage_validation_rejects_non_directory_ancestors_and_non_regular_state_nodes;
mod support;
mod target_load_lock_and_invalid_storage_failures_are_reported_without_hidden_fallbacks;
mod text_measurements_preserve_configured_projection_identity;
mod v2_runtime_handles_disabled_contract_mismatch_and_owned_lock_boundaries;
mod valid_issue_outcomes_persist_without_blocking_accepted_state_advancement;
mod valid_overflow_outcomes_persist_without_blocking_accepted_state_advancement;
